language:       ruby
osx_image:      xcode10.1
install:
  # Install Jazzy and dependencies
  - gem install jazzy
script:
  - "jazzy --clean --no-objc --author Arthur Guiot --author_url https://arguiot.com --github_url https://github.com/orionsearch/SearchKit-Swift --output docs --xcodebuild-arguments -project,SearchKit-Swift.xcodeproj,-scheme,SearchKit-Swift -m SearchKit_Swift"

deploy:
  provider:     pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir:    docs
  on:
    branch:     master
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
